name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  test_RyhmesWorldWide:
    timeout-minutes: 60
    environment: RyhmesWorldWide
    runs-on: ubuntu-latest

    env:
      GHOST_LAB_URL: ${{ secrets.GHOST_LAB_URL }}
      GHOST_LAB_USERNAME: ${{ secrets.GHOST_LAB_USERNAME }}
      GHOST_LAB_PASSWORD: ${{ secrets.GHOST_LAB_PASSWORD }}
 
    steps:
    - uses: ./.github/actions/setup-playwright

  test_BestQuestGames:
    timeout-minutes: 60
    environment: BestQuestGames
    runs-on: ubuntu-latest

    env:
      GHOST_LAB_URL: ${{ secrets.GHOST_LAB_URL }}
      GHOST_LAB_USERNAME: ${{ secrets.GHOST_LAB_USERNAME }}
      GHOST_LAB_PASSWORD: ${{ secrets.GHOST_LAB_PASSWORD }}
 
    steps:
    - uses: ./.github/actions/setup-playwright
